version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    restart: always

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DB_CONNSTR: ${DB_CONNSTR}
      - URL: ${URL}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  postgres-db-volume:
  app-volume: